//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_USER_DOCUMENT
    {
        public TBL_MAS_USER_DOCUMENT()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _UserID;
        public virtual int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }

        /// Column Comment...
        private string _UserName;
        public virtual string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this._UserName = value;
            }
        }

        /// Column Comment...
        private string _DocumnetType;
        public virtual string DocumnetType
        {
            get
            {
                return this._DocumnetType;
            }
            set
            {
                this._DocumnetType = value;
            }
        }

        /// Column Comment...
        private System.String? _Description;
        public virtual System.String? Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }

        /// Column Comment...
        private DateTime? _DocDateTime;
        public virtual DateTime? DocDateTime
        {
            get
            {
                return this._DocDateTime;
            }
            set
            {
                this._DocDateTime = value;
            }
        }

        /// Column Comment...
        private System.String? _DocumentURL;
        public virtual System.String? DocumentURL
        {
            get
            {
                return this._DocumentURL;
            }
            set
            {
                this._DocumentURL = value;
            }
        }

        /// Column Comment...
        private System.String? _DocExtension;
        public virtual System.String? DocExtension
        {
            get
            {
                return this._DocExtension;
            }
            set
            {
                this._DocExtension = value;
            }
        }

        /// Column Comment...
        private System.String? _FilePath;
        public virtual System.String? FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private System.Boolean? _IsActive;
        public virtual System.Boolean? IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
