//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_LOCATION_CITY
    {
        public TBL_MAS_LOCATION_CITY()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private System.String? _Name;
        public virtual System.String? Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// Column Comment...
        private int _CountryID;
        public virtual int CountryID
        {
            get
            {
                return this._CountryID;
            }
            set
            {
                this._CountryID = value;
            }
        }

        /// Column Comment...
        private int _StateID;
        public virtual int StateID
        {
            get
            {
                return this._StateID;
            }
            set
            {
                this._StateID = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
