//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_USER_LOGIN
    {
        public TBL_MAS_USER_LOGIN()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _UserID;
        public virtual int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }

        /// Column Comment...
        private string _UserLoginName;
        public virtual string UserLoginName
        {
            get
            {
                return this._UserLoginName;
            }
            set
            {
                this._UserLoginName = value;
            }
        }

        /// Column Comment...
        private int _UserRoleID;
        public virtual int UserRoleID
        {
            get
            {
                return this._UserRoleID;
            }
            set
            {
                this._UserRoleID = value;
            }
        }

        /// Column Comment...
        private string _UserRoleName;
        public virtual string UserRoleName
        {
            get
            {
                return this._UserRoleName;
            }
            set
            {
                this._UserRoleName = value;
            }
        }

        /// Column Comment...
        private string _Password;
        public virtual string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this._Password = value;
            }
        }

        /// Column Comment...
        private System.String? _PrevPassword1;
        public virtual System.String? PrevPassword1
        {
            get
            {
                return this._PrevPassword1;
            }
            set
            {
                this._PrevPassword1 = value;
            }
        }

        /// Column Comment...
        private System.String? _PrevPassword2;
        public virtual System.String? PrevPassword2
        {
            get
            {
                return this._PrevPassword2;
            }
            set
            {
                this._PrevPassword2 = value;
            }
        }

        /// Column Comment...
        private System.String? _PrevPassword3;
        public virtual System.String? PrevPassword3
        {
            get
            {
                return this._PrevPassword3;
            }
            set
            {
                this._PrevPassword3 = value;
            }
        }

        /// Column Comment...
        private System.String? _PrevPassword4;
        public virtual System.String? PrevPassword4
        {
            get
            {
                return this._PrevPassword4;
            }
            set
            {
                this._PrevPassword4 = value;
            }
        }

        /// Column Comment...
        private System.String? _PrevPassword5;
        public virtual System.String? PrevPassword5
        {
            get
            {
                return this._PrevPassword5;
            }
            set
            {
                this._PrevPassword5 = value;
            }
        }

        /// Column Comment...
        private System.String? _SecretQuestion;
        public virtual System.String? SecretQuestion
        {
            get
            {
                return this._SecretQuestion;
            }
            set
            {
                this._SecretQuestion = value;
            }
        }

        /// Column Comment...
        private System.String? _SecretAnswer;
        public virtual System.String? SecretAnswer
        {
            get
            {
                return this._SecretAnswer;
            }
            set
            {
                this._SecretAnswer = value;
            }
        }

        /// Column Comment...
        private int? _UserCategoryID;
        public virtual int? UserCategoryID
        {
            get
            {
                return this._UserCategoryID;
            }
            set
            {
                this._UserCategoryID = value;
            }
        }

        /// Column Comment...
        private System.String? _UserCategoryName;
        public virtual System.String? UserCategoryName
        {
            get
            {
                return this._UserCategoryName;
            }
            set
            {
                this._UserCategoryName = value;
            }
        }

        /// Column Comment...
        private DateTime? _LastPasswordChange;
        public virtual DateTime? LastPasswordChange
        {
            get
            {
                return this._LastPasswordChange;
            }
            set
            {
                this._LastPasswordChange = value;
            }
        }

        /// Column Comment...
        private System.String? _ResetPasswordFlag;
        public virtual System.String? ResetPasswordFlag
        {
            get
            {
                return this._ResetPasswordFlag;
            }
            set
            {
                this._ResetPasswordFlag = value;
            }
        }

        /// Column Comment...
        private DateTime? _LastLoginDateTime;
        public virtual DateTime? LastLoginDateTime
        {
            get
            {
                return this._LastLoginDateTime;
            }
            set
            {
                this._LastLoginDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsLoginActive;
        public virtual bool IsLoginActive
        {
            get
            {
                return this._IsLoginActive;
            }
            set
            {
                this._IsLoginActive = value;
            }
        }

        /// Column Comment...
        private System.Boolean? _IsLoginLocked;
        public virtual System.Boolean? IsLoginLocked
        {
            get
            {
                return this._IsLoginLocked;
            }
            set
            {
                this._IsLoginLocked = value;
            }
        }

        /// Column Comment...
        private System.String? _LastLoginIPAddress;
        public virtual System.String? LastLoginIPAddress
        {
            get
            {
                return this._LastLoginIPAddress;
            }
            set
            {
                this._LastLoginIPAddress = value;
            }
        }

        /// Column Comment...
        private System.String? _LastLoginMachineName;
        public virtual System.String? LastLoginMachineName
        {
            get
            {
                return this._LastLoginMachineName;
            }
            set
            {
                this._LastLoginMachineName = value;
            }
        }

        /// Column Comment...
        private System.String? _LastLoginMachineDetails;
        public virtual System.String? LastLoginMachineDetails
        {
            get
            {
                return this._LastLoginMachineDetails;
            }
            set
            {
                this._LastLoginMachineDetails = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
