//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_USER
    {
        public TBL_MAS_USER()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private string _UserNumber;
        public virtual string UserNumber
        {
            get
            {
                return this._UserNumber;
            }
            set
            {
                this._UserNumber = value;
            }
        }

        /// Column Comment...
        private int _DepartmentID;
        public virtual int DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                this._DepartmentID = value;
            }
        }

        /// Column Comment...
        private int _DesignationID;
        public virtual int DesignationID
        {
            get
            {
                return this._DesignationID;
            }
            set
            {
                this._DesignationID = value;
            }
        }

        /// Column Comment...
        private int? _BranchID;
        public virtual int? BranchID
        {
            get
            {
                return this._BranchID;
            }
            set
            {
                this._BranchID = value;
            }
        }

        /// Column Comment...
        private int? _ContracterID;
        public virtual int? ContracterID
        {
            get
            {
                return this._ContracterID;
            }
            set
            {
                this._ContracterID = value;
            }
        }

        /// Column Comment...
        private System.String? _EmployeementType;
        public virtual System.String? EmployeementType
        {
            get
            {
                return this._EmployeementType;
            }
            set
            {
                this._EmployeementType = value;
            }
        }

        /// Column Comment...
        private string _FirstName;
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this._FirstName = value;
            }
        }

        /// Column Comment...
        private string _LastName;
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this._LastName = value;
            }
        }

        /// Column Comment...
        private System.String? _Gender;
        public virtual System.String? Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this._Gender = value;
            }
        }

        /// Column Comment...
        private DateTime? _DateOfBirth;
        public virtual DateTime? DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this._DateOfBirth = value;
            }
        }

        /// Column Comment...
        private System.String? _NationalIdentificationNumber;
        public virtual System.String? NationalIdentificationNumber
        {
            get
            {
                return this._NationalIdentificationNumber;
            }
            set
            {
                this._NationalIdentificationNumber = value;
            }
        }

        /// Column Comment...
        private int? _LanguageID;
        public virtual int? LanguageID
        {
            get
            {
                return this._LanguageID;
            }
            set
            {
                this._LanguageID = value;
            }
        }

        /// Column Comment...
        private System.String? _Language;
        public virtual System.String? Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this._Language = value;
            }
        }

        /// Column Comment...
        private System.String? _Address;
        public virtual System.String? Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }

        /// Column Comment...
        private System.String? _Area;
        public virtual System.String? Area
        {
            get
            {
                return this._Area;
            }
            set
            {
                this._Area = value;
            }
        }

        /// Column Comment...
        private int? _CityID;
        public virtual int? CityID
        {
            get
            {
                return this._CityID;
            }
            set
            {
                this._CityID = value;
            }
        }

        /// Column Comment...
        private System.String? _CityName;
        public virtual System.String? CityName
        {
            get
            {
                return this._CityName;
            }
            set
            {
                this._CityName = value;
            }
        }

        /// Column Comment...
        private System.String? _PostalCode;
        public virtual System.String? PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this._PostalCode = value;
            }
        }

        /// Column Comment...
        private int? _StateID;
        public virtual int? StateID
        {
            get
            {
                return this._StateID;
            }
            set
            {
                this._StateID = value;
            }
        }

        /// Column Comment...
        private System.String? _StateName;
        public virtual System.String? StateName
        {
            get
            {
                return this._StateName;
            }
            set
            {
                this._StateName = value;
            }
        }

        /// Column Comment...
        private int? _CountryID;
        public virtual int? CountryID
        {
            get
            {
                return this._CountryID;
            }
            set
            {
                this._CountryID = value;
            }
        }

        /// Column Comment...
        private System.String? _CountryName;
        public virtual System.String? CountryName
        {
            get
            {
                return this._CountryName;
            }
            set
            {
                this._CountryName = value;
            }
        }

        /// Column Comment...
        private System.String? _PhonePrimary;
        public virtual System.String? PhonePrimary
        {
            get
            {
                return this._PhonePrimary;
            }
            set
            {
                this._PhonePrimary = value;
            }
        }

        /// Column Comment...
        private System.String? _Email;
        public virtual System.String? Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }

        /// Column Comment...
        private DateTime? _DateOfJoining;
        public virtual DateTime? DateOfJoining
        {
            get
            {
                return this._DateOfJoining;
            }
            set
            {
                this._DateOfJoining = value;
            }
        }

        /// Column Comment...
        private System.String? _EmploymentStatus;
        public virtual System.String? EmploymentStatus
        {
            get
            {
                return this._EmploymentStatus;
            }
            set
            {
                this._EmploymentStatus = value;
            }
        }

        /// Column Comment...
        private System.Boolean? _IsThereSignatureImage;
        public virtual System.Boolean? IsThereSignatureImage
        {
            get
            {
                return this._IsThereSignatureImage;
            }
            set
            {
                this._IsThereSignatureImage = value;
            }
        }

        /// Column Comment...
        private System.String? _SignatureImageURL;
        public virtual System.String? SignatureImageURL
        {
            get
            {
                return this._SignatureImageURL;
            }
            set
            {
                this._SignatureImageURL = value;
            }
        }

        /// Column Comment...
        private System.String? _AccessCardNumber;
        public virtual System.String? AccessCardNumber
        {
            get
            {
                return this._AccessCardNumber;
            }
            set
            {
                this._AccessCardNumber = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
