//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_REL_APP_ROLE_FEATURE
    {
        public TBL_REL_APP_ROLE_FEATURE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _RoleID;
        public virtual int RoleID
        {
            get
            {
                return this._RoleID;
            }
            set
            {
                this._RoleID = value;
            }
        }

        /// Column Comment...
        private string _RoleName;
        public virtual string RoleName
        {
            get
            {
                return this._RoleName;
            }
            set
            {
                this._RoleName = value;
            }
        }

        /// Column Comment...
        private int _AppFeatureID;
        public virtual int AppFeatureID
        {
            get
            {
                return this._AppFeatureID;
            }
            set
            {
                this._AppFeatureID = value;
            }
        }

        /// Column Comment...
        private string _AppFeatureName;
        public virtual string AppFeatureName
        {
            get
            {
                return this._AppFeatureName;
            }
            set
            {
                this._AppFeatureName = value;
            }
        }

        /// Column Comment...
        private System.String? _Type;
        public virtual System.String? Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this._Type = value;
            }
        }

        /// Column Comment...
        private System.String? _Permission;
        public virtual System.String? Permission
        {
            get
            {
                return this._Permission;
            }
            set
            {
                this._Permission = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private System.Boolean? _IsActive;
        public virtual System.Boolean? IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
