//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_TRN_USER_CERTIFICATE
    {
        public TBL_TRN_USER_CERTIFICATE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _CertificateID;
        public virtual int CertificateID
        {
            get
            {
                return this._CertificateID;
            }
            set
            {
                this._CertificateID = value;
            }
        }

        /// Column Comment...
        private int _UserID;
        public virtual int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }

        /// Column Comment...
        private int? _ModuleID;
        public virtual int? ModuleID
        {
            get
            {
                return this._ModuleID;
            }
            set
            {
                this._ModuleID = value;
            }
        }

        /// Column Comment...
        private DateTime _IssueDate;
        public virtual DateTime IssueDate
        {
            get
            {
                return this._IssueDate;
            }
            set
            {
                this._IssueDate = value;
            }
        }

        /// Column Comment...
        private System.String? _CertificateURL;
        public virtual System.String? CertificateURL
        {
            get
            {
                return this._CertificateURL;
            }
            set
            {
                this._CertificateURL = value;
            }
        }

        /// Column Comment...
        private System.String? _QRCodeURL;
        public virtual System.String? QRCodeURL
        {
            get
            {
                return this._QRCodeURL;
            }
            set
            {
                this._QRCodeURL = value;
            }
        }

        /// Column Comment...
        private System.String? _VerificationCode;
        public virtual System.String? VerificationCode
        {
            get
            {
                return this._VerificationCode;
            }
            set
            {
                this._VerificationCode = value;
            }
        }

        /// Column Comment...
        private bool _IsRevoked;
        public virtual bool IsRevoked
        {
            get
            {
                return this._IsRevoked;
            }
            set
            {
                this._IsRevoked = value;
            }
        }

        /// Column Comment...
        private System.String? _Remarks;
        public virtual System.String? Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                this._Remarks = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
