//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_APP_MODULE_LICENSE
    {
        public TBL_MAS_APP_MODULE_LICENSE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _ModuleID;
        public virtual int ModuleID
        {
            get
            {
                return this._ModuleID;
            }
            set
            {
                this._ModuleID = value;
            }
        }

        /// Column Comment...
        private string _ModuleName;
        public virtual string ModuleName
        {
            get
            {
                return this._ModuleName;
            }
            set
            {
                this._ModuleName = value;
            }
        }

        /// Column Comment...
        private bool _IsLicenced;
        public virtual bool IsLicenced
        {
            get
            {
                return this._IsLicenced;
            }
            set
            {
                this._IsLicenced = value;
            }
        }

        /// Column Comment...
        private int? _NumberOfUserLicences;
        public virtual int? NumberOfUserLicences
        {
            get
            {
                return this._NumberOfUserLicences;
            }
            set
            {
                this._NumberOfUserLicences = value;
            }
        }

        /// Column Comment...
        private int? _NumberOfUsedLicences;
        public virtual int? NumberOfUsedLicences
        {
            get
            {
                return this._NumberOfUsedLicences;
            }
            set
            {
                this._NumberOfUsedLicences = value;
            }
        }

        /// Column Comment...
        private int? _NumberOfAvailableLicences;
        public virtual int? NumberOfAvailableLicences
        {
            get
            {
                return this._NumberOfAvailableLicences;
            }
            set
            {
                this._NumberOfAvailableLicences = value;
            }
        }

        /// Column Comment...
        private System.String? _LicenceTermsAndConditions;
        public virtual System.String? LicenceTermsAndConditions
        {
            get
            {
                return this._LicenceTermsAndConditions;
            }
            set
            {
                this._LicenceTermsAndConditions = value;
            }
        }

        /// Column Comment...
        private int _BranchID;
        public virtual int BranchID
        {
            get
            {
                return this._BranchID;
            }
            set
            {
                this._BranchID = value;
            }
        }

        /// Column Comment...
        private int _DepartmentID;
        public virtual int DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                this._DepartmentID = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
