//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_TRN_EVENT_PARTICIPANT
    {
        public TBL_TRN_EVENT_PARTICIPANT()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _EventID;
        public virtual int EventID
        {
            get
            {
                return this._EventID;
            }
            set
            {
                this._EventID = value;
            }
        }

        /// Column Comment...
        private int _UserID;
        public virtual int UserID
        {
            get
            {
                return this._UserID;
            }
            set
            {
                this._UserID = value;
            }
        }

        /// Column Comment...
        private string _ParticipantName;
        public virtual string ParticipantName
        {
            get
            {
                return this._ParticipantName;
            }
            set
            {
                this._ParticipantName = value;
            }
        }

        /// Column Comment...
        private System.String? _Email;
        public virtual System.String? Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }

        /// Column Comment...
        private System.String? _Phone;
        public virtual System.String? Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this._Phone = value;
            }
        }

        /// Column Comment...
        private System.String? _Designation;
        public virtual System.String? Designation
        {
            get
            {
                return this._Designation;
            }
            set
            {
                this._Designation = value;
            }
        }

        /// Column Comment...
        private System.String? _Organization;
        public virtual System.String? Organization
        {
            get
            {
                return this._Organization;
            }
            set
            {
                this._Organization = value;
            }
        }

        /// Column Comment...
        private System.Boolean? _IsAttended;
        public virtual System.Boolean? IsAttended
        {
            get
            {
                return this._IsAttended;
            }
            set
            {
                this._IsAttended = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
