//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_CERTIFICATE
    {
        public TBL_MAS_CERTIFICATE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private string _Name;
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// Column Comment...
        private string _CertificateType;
        public virtual string CertificateType
        {
            get
            {
                return this._CertificateType;
            }
            set
            {
                this._CertificateType = value;
            }
        }

        /// Column Comment...
        private int? _ModuleID;
        public virtual int? ModuleID
        {
            get
            {
                return this._ModuleID;
            }
            set
            {
                this._ModuleID = value;
            }
        }

        /// Column Comment...
        private System.String? _TemplateFilePath;
        public virtual System.String? TemplateFilePath
        {
            get
            {
                return this._TemplateFilePath;
            }
            set
            {
                this._TemplateFilePath = value;
            }
        }

        /// Column Comment...
        private System.String? _DigitalSignatureURL;
        public virtual System.String? DigitalSignatureURL
        {
            get
            {
                return this._DigitalSignatureURL;
            }
            set
            {
                this._DigitalSignatureURL = value;
            }
        }

        /// Column Comment...
        private bool _IncludeQRCode;
        public virtual bool IncludeQRCode
        {
            get
            {
                return this._IncludeQRCode;
            }
            set
            {
                this._IncludeQRCode = value;
            }
        }

        /// Column Comment...
        private System.String? _VerificationURL;
        public virtual System.String? VerificationURL
        {
            get
            {
                return this._VerificationURL;
            }
            set
            {
                this._VerificationURL = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
