//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_ORGANIZATION_BRANCH
    {
        public TBL_MAS_ORGANIZATION_BRANCH()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private string _Name;
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// Column Comment...
        private string _BranchCode;
        public virtual string BranchCode
        {
            get
            {
                return this._BranchCode;
            }
            set
            {
                this._BranchCode = value;
            }
        }

        /// Column Comment...
        private System.String? _Description;
        public virtual System.String? Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this._Description = value;
            }
        }

        /// Column Comment...
        private System.String? _Address;
        public virtual System.String? Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }

        /// Column Comment...
        private System.String? _City;
        public virtual System.String? City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

        /// Column Comment...
        private System.String? _State;
        public virtual System.String? State
        {
            get
            {
                return this._State;
            }
            set
            {
                this._State = value;
            }
        }

        /// Column Comment...
        private System.String? _Country;
        public virtual System.String? Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this._Country = value;
            }
        }

        /// Column Comment...
        private System.String? _PostalCode;
        public virtual System.String? PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this._PostalCode = value;
            }
        }

        /// Column Comment...
        private System.String? _PhonePrimary;
        public virtual System.String? PhonePrimary
        {
            get
            {
                return this._PhonePrimary;
            }
            set
            {
                this._PhonePrimary = value;
            }
        }

        /// Column Comment...
        private System.String? _Email;
        public virtual System.String? Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
