//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_ORGANIZATION
    {
        public TBL_MAS_ORGANIZATION()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private string _Name;
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// Column Comment...
        private string _ShortName;
        public virtual string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this._ShortName = value;
            }
        }

        /// Column Comment...
        private string _RegisteredName;
        public virtual string RegisteredName
        {
            get
            {
                return this._RegisteredName;
            }
            set
            {
                this._RegisteredName = value;
            }
        }

        /// Column Comment...
        private string _ApplicationType;
        public virtual string ApplicationType
        {
            get
            {
                return this._ApplicationType;
            }
            set
            {
                this._ApplicationType = value;
            }
        }

        /// Column Comment...
        private System.String? _NameDisplayOption;
        public virtual System.String? NameDisplayOption
        {
            get
            {
                return this._NameDisplayOption;
            }
            set
            {
                this._NameDisplayOption = value;
            }
        }

        /// Column Comment...
        private System.String? _Address;
        public virtual System.String? Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this._Address = value;
            }
        }

        /// Column Comment...
        private System.String? _City;
        public virtual System.String? City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

        /// Column Comment...
        private System.String? _State;
        public virtual System.String? State
        {
            get
            {
                return this._State;
            }
            set
            {
                this._State = value;
            }
        }

        /// Column Comment...
        private System.String? _Country;
        public virtual System.String? Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this._Country = value;
            }
        }

        /// Column Comment...
        private System.String? _PostalCode;
        public virtual System.String? PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this._PostalCode = value;
            }
        }

        /// Column Comment...
        private System.String? _PhonePrimary;
        public virtual System.String? PhonePrimary
        {
            get
            {
                return this._PhonePrimary;
            }
            set
            {
                this._PhonePrimary = value;
            }
        }

        /// Column Comment...
        private System.String? _PhoneSecondary;
        public virtual System.String? PhoneSecondary
        {
            get
            {
                return this._PhoneSecondary;
            }
            set
            {
                this._PhoneSecondary = value;
            }
        }

        /// Column Comment...
        private System.String? _Email;
        public virtual System.String? Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this._Email = value;
            }
        }

        /// Column Comment...
        private System.String? _URL;
        public virtual System.String? URL
        {
            get
            {
                return this._URL;
            }
            set
            {
                this._URL = value;
            }
        }

        /// Column Comment...
        private System.String? _LogoURL;
        public virtual System.String? LogoURL
        {
            get
            {
                return this._LogoURL;
            }
            set
            {
                this._LogoURL = value;
            }
        }

        /// Column Comment...
        private System.String? _LogoShortURL;
        public virtual System.String? LogoShortURL
        {
            get
            {
                return this._LogoShortURL;
            }
            set
            {
                this._LogoShortURL = value;
            }
        }

        /// Column Comment...
        private System.String? _RZP_KEY;
        public virtual System.String? RZP_KEY
        {
            get
            {
                return this._RZP_KEY;
            }
            set
            {
                this._RZP_KEY = value;
            }
        }

        /// Column Comment...
        private System.String? _RZP_SECRET;
        public virtual System.String? RZP_SECRET
        {
            get
            {
                return this._RZP_SECRET;
            }
            set
            {
                this._RZP_SECRET = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
