//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_APP_FEATURE_LICENSE
    {
        public TBL_MAS_APP_FEATURE_LICENSE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private int _ModuleID;
        public virtual int ModuleID
        {
            get
            {
                return this._ModuleID;
            }
            set
            {
                this._ModuleID = value;
            }
        }

        /// Column Comment...
        private int? _MaxUserCreation;
        public virtual int? MaxUserCreation
        {
            get
            {
                return this._MaxUserCreation;
            }
            set
            {
                this._MaxUserCreation = value;
            }
        }

        /// Column Comment...
        private int? _MaxUserAllowed;
        public virtual int? MaxUserAllowed
        {
            get
            {
                return this._MaxUserAllowed;
            }
            set
            {
                this._MaxUserAllowed = value;
            }
        }

        /// Column Comment...
        private System.String? _SerialNumber;
        public virtual System.String? SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this._SerialNumber = value;
            }
        }

        /// Column Comment...
        private System.String? _LicenseKey;
        public virtual System.String? LicenseKey
        {
            get
            {
                return this._LicenseKey;
            }
            set
            {
                this._LicenseKey = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int _UpdatedUserID;
        public virtual int UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
