//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.Common;


namespace AP.CHRP.XRDB.DB.DataTable
{
    
    public partial class TBL_MAS_APP_FEATURE
    {
        public TBL_MAS_APP_FEATURE()
        {
        }

        /// Column Comment...
        private int _ID;
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// Column Comment...
        private string _Name;
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// Column Comment...
        private int _ModuleID;
        public virtual int ModuleID
        {
            get
            {
                return this._ModuleID;
            }
            set
            {
                this._ModuleID = value;
            }
        }

        /// Column Comment...
        private System.String? _ControllerName;
        public virtual System.String? ControllerName
        {
            get
            {
                return this._ControllerName;
            }
            set
            {
                this._ControllerName = value;
            }
        }

        /// Column Comment...
        private System.String? _FeatureDescription;
        public virtual System.String? FeatureDescription
        {
            get
            {
                return this._FeatureDescription;
            }
            set
            {
                this._FeatureDescription = value;
            }
        }

        /// Column Comment...
        private System.String? _ActionMethodName;
        public virtual System.String? ActionMethodName
        {
            get
            {
                return this._ActionMethodName;
            }
            set
            {
                this._ActionMethodName = value;
            }
        }

        /// Column Comment...
        private System.String? _ActionMethodType;
        public virtual System.String? ActionMethodType
        {
            get
            {
                return this._ActionMethodType;
            }
            set
            {
                this._ActionMethodType = value;
            }
        }

        /// Column Comment...
        private System.String? _ActionMethodInputType;
        public virtual System.String? ActionMethodInputType
        {
            get
            {
                return this._ActionMethodInputType;
            }
            set
            {
                this._ActionMethodInputType = value;
            }
        }

        /// Column Comment...
        private System.String? _DefaultBackURL;
        public virtual System.String? DefaultBackURL
        {
            get
            {
                return this._DefaultBackURL;
            }
            set
            {
                this._DefaultBackURL = value;
            }
        }

        /// Column Comment...
        private System.String? _IPDC;
        public virtual System.String? IPDC
        {
            get
            {
                return this._IPDC;
            }
            set
            {
                this._IPDC = value;
            }
        }

        /// Column Comment...
        private System.String? _OPDC;
        public virtual System.String? OPDC
        {
            get
            {
                return this._OPDC;
            }
            set
            {
                this._OPDC = value;
            }
        }

        /// Column Comment...
        private System.String? _CodingComments;
        public virtual System.String? CodingComments
        {
            get
            {
                return this._CodingComments;
            }
            set
            {
                this._CodingComments = value;
            }
        }

        /// Column Comment...
        private int _CreatedUserID;
        public virtual int CreatedUserID
        {
            get
            {
                return this._CreatedUserID;
            }
            set
            {
                this._CreatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime _CreatedDateTime;
        public virtual DateTime CreatedDateTime
        {
            get
            {
                return this._CreatedDateTime;
            }
            set
            {
                this._CreatedDateTime = value;
            }
        }

        /// Column Comment...
        private int? _UpdatedUserID;
        public virtual int? UpdatedUserID
        {
            get
            {
                return this._UpdatedUserID;
            }
            set
            {
                this._UpdatedUserID = value;
            }
        }

        /// Column Comment...
        private DateTime? _UpdatedDateTime;
        public virtual DateTime? UpdatedDateTime
        {
            get
            {
                return this._UpdatedDateTime;
            }
            set
            {
                this._UpdatedDateTime = value;
            }
        }

        /// Column Comment...
        private bool _IsActive;
        public virtual bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this._IsActive = value;
            }
        }
    }
}
